#!/usr/bin/env python

import sys
import argparse
from modules.user import *

def print_help():
    """ Prints out the help message """
    tmp = "Usage: hadmin <command> <command options>\n\n"
    tmp = tmp + "Commands:\n"
    tmp = tmp + "\t- useradd\n"
    tmp = tmp + "\t- queueadd\n"
    tmp = tmp + "\t- userdel\n"
    tmp = tmp + "\t- queuedel\n"
    print(tmp)

def run():
    command = sys.argv[1]

    sysargs = sys.argv[2:]
    if command == 'useradd':
        useradd(sysargs, None)

if __name__ == "__main__":
    run()
