#!/usr/bin/env python

import argparse

def print_help():
    """ Prints out the help message """
    tmp = "Usage: hadmin <command> <command options>\n\n"
    tmp = tmp + "Commands:\n"
    tmp = tmp + "\t- useradd\n"
    tmp = tmp + "\t- queueadd\n"
    tmp = tmp + "\t- userdel\n"
    tmp = tmp + "\t- queuedel\n"
    print(tmp)

def run():
    parser = argparse.ArgumentParser(
            description="HAdmin: Hadoop administration tool")
    parser.add_argument('-v', '--verbose', action='count',
            help='Display verbose output')
    parser.add_argument('command', metavar='COMMAND', type=str, nargs=1,
            help='One of useradd, userdel, queueadd, queuedel')
    args = parser.parse_args()

if __name__ == "__main__":
    run()
